import 'package:citytocoast_app/screens/Authscreen.dart';
import 'package:flutter/material.dart';

// Firebase imports
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

import 'screens/verification_screen.dart';
import 'screens/homepage_client.dart';
import 'screens/chat_screen.dart';
import 'screens/sitter.dart';
import 'screens/community_feed.dart';
import 'screens/create_post_screen.dart';
import 'screens/emergency_booking_screen.dart';
import 'screens/emergency_details_screen.dart';
import 'screens/payment_screen.dart';
import 'screens/admin/admin_dashboard_screen.dart';

Future<void> main() async {
  // Required before Firebase init
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const CityToCoastApp());
}

class CityToCoastApp extends StatelessWidget {
  const CityToCoastApp({super.key});

  @override
  Widget build(BuildContext context) {
    final appTheme = ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: Colors.white,
      colorScheme: ColorScheme.fromSeed(
        seedColor: Colors.blue,
        brightness: Brightness.light,
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      cardColor: Colors.white,
    );

    return MaterialApp(
      title: 'City to Coast App',
      theme: appTheme,
      initialRoute: '/',
      routes: {
        '/': (context) => const AuthScreen(),
        '/verify': (context) => VerificationScreen(),
        '/clientHome': (context) => HomePageScreen(),
        '/chat': (context) => ChatScreen(),

        // Quick Action Routes
        '/communityFeed': (context) => const CommunityFeedScreen(),
        '/createPost': (context) => const CreatePostScreen(),
        '/emergencyBooking': (context) => const EmergencyBookingScreen(),
        '/emergencyDetails': (context) {
          final sitter = ModalRoute.of(context)!.settings.arguments as Sitter;
          return EmergencyDetailsScreen(sitter: sitter);
        },

        // Admin Dashboard
        '/adminDashboard': (context) => const AdminDashboardScreen(),
      },
    );
  }
}
