import 'package:citytocoast_app/screens/Authscreen.dart';

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';

// Firebase imports
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

import 'screens/verification_screen.dart';
import 'screens/homepage_client.dart';
import 'screens/chat_screen.dart';
import 'screens/sitter.dart';
import 'screens/community_feed.dart';
import 'screens/create_post_screen.dart';
import 'screens/emergency_booking_screen.dart';
import 'screens/emergency_details_screen.dart';
import 'screens/my_bookings_screen.dart';
import 'screens/admin/admin_dashboard_screen.dart';
import 'dev/seed_sitters.dart';
import 'screens/favorites_screen.dart';
import 'screens/sitter_profile_page.dart';

// Stripe keys are now loaded from .env
String get _stripePublishableKey => dotenv.env['STRIPE_PUBLISHABLE_KEY'] ?? '';

Future<void> main() async {
  // Required before Firebase init
  WidgetsFlutterBinding.ensureInitialized();

  // Load environment variables
  await dotenv.load(fileName: ".env");

  Stripe.publishableKey = _stripePublishableKey;
  Stripe.merchantIdentifier = 'merchant.com.citytocoast';
  Stripe.urlScheme = 'citytocoast';
  await Stripe.instance.applySettings();

  // Initialize Firebase
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  if (kDebugMode) {
    const emulatorHost = '10.0.2.2'; // Android emulator = host machine
    const emulatorPort = 5002;

    FirebaseFunctions.instance.useFunctionsEmulator(emulatorHost, emulatorPort);

    debugPrint('🔧 Firebase Functions Emulator Config:');
    debugPrint('   → Host: $emulatorHost (Android emulator → host)');
    debugPrint('   → Port: $emulatorPort');
    debugPrint('');
    debugPrint('💡 Ensure emulator is running:');
    debugPrint('   firebase emulators:start');
    debugPrint('');
  }

  final bool runSeeder =
      kDebugMode &&
      const bool.fromEnvironment('RUN_SEED_SITTERS', defaultValue: false);
  if (runSeeder) {
    await seedSitters();
  }

  runApp(const CityToCoastApp());
}

class CityToCoastApp extends StatelessWidget {
  const CityToCoastApp({super.key});

  @override
  Widget build(BuildContext context) {
    final appTheme = ThemeData(
      brightness: Brightness.light,
      scaffoldBackgroundColor: Colors.white,
      colorScheme: ColorScheme.fromSeed(
        seedColor: Colors.blue,
        brightness: Brightness.light,
      ),
      appBarTheme: const AppBarTheme(
        backgroundColor: Colors.white,
        foregroundColor: Colors.black,
        elevation: 0,
      ),
      cardColor: Colors.white,
    );

    return MaterialApp(
      title: 'City to Coast App',
      theme: appTheme,
      initialRoute: '/',
      routes: {
        '/': (context) => const AuthScreen(),
        '/verify': (context) => VerificationScreen(),
        '/clientHome': (context) => HomePageScreen(),

        '/chat': (context) {
          final args =
              ModalRoute.of(context)!.settings.arguments
                  as Map<String, dynamic>;
          return ChatScreen(
            roomId: args['roomId'],
            recipientName: args['recipientName'],
            recipientPhoto: args['recipientPhoto'],
          );
        },
        '/myBookings': (context) => const MyBookingsScreen(),
        '/favorites': (context) => const FavoritesScreen(),
        '/sitterProfile': (context) {
          final args = ModalRoute.of(context)!.settings.arguments;
          if (args is Map<String, dynamic>) {
            return SitterProfilePage(
              sitter: args['sitter'] as Sitter,
              isEmergency: args['isEmergency'] as bool? ?? false,
            );
          }
          return SitterProfilePage(sitter: args as Sitter);
        },

        // Quick Action Routes
        '/communityFeed': (context) => const CommunityFeedScreen(),
        '/createPost': (context) => const CreatePostScreen(),
        '/emergencyBooking': (context) => const EmergencyBookingScreen(),
        '/emergencyDetails': (context) {
          final sitter = ModalRoute.of(context)!.settings.arguments as Sitter;
          return EmergencyDetailsScreen(sitter: sitter);
        },

        // Admin Dashboard
        '/adminDashboard': (context) => const AdminDashboardScreen(),
      },
    );
  }
}
