import 'sitter.dart';

final List<Sitter> sitterList = [
  Sitter(
    name: "Sarah Johnson",
    rating: 4.9,
    reviews: 127,
    ratePerHour: 25,
    bio: "Experienced babysitter with newborn care expertise.",
    specialties: ["Babysitting", "Newborn Care"],
    availability: ["Mon", "Tue", "Wed"],
    distance: 0.8,
    tags: ["baby"],
    img: "https://i.pravatar.cc/150?img=14",
  ),
  Sitter(
    name: "Mike Chen",
    rating: 4.8,
    reviews: 89,
    ratePerHour: 20,
    bio: "Pet lover, certified in dog walking & care.",
    specialties: ["Pet Sitting", "Dog Walking"],
    availability: ["Thu", "Fri", "Sat"],
    distance: 1.2,
    tags: ["pet"],
    img: "https://i.pravatar.cc/150?img=12",
  ),
  Sitter(
    name: "Emma Rodriguez",
    rating: 4.9,
    reviews: 203,
    ratePerHour: 28,
    bio: "Flexible sitter for both kids and pets.",
    specialties: ["Babysitting", "Pet Sitting"],
    availability: ["Sun", "Mon", "Wed"],
    distance: 0.5,
    tags: ["baby", "pet"],
    img: "https://i.pravatar.cc/150?img=45",
  ),
  Sitter(
    name: "Liam Brown",
    rating: 4.4,
    reviews: 75,
    ratePerHour: 23,
    bio: "Energetic sitter great with kids and pets.",
    specialties: ["Babysitting", "Pet Sitting"],
    availability: ["Tue", "Thu"],
    distance: 2.0,
    tags: ["baby", "pet"],
    img: "https://i.pravatar.cc/150?img=65",
  ),
  Sitter(
    name: "Sophia Davis",
    rating: 4.7,
    reviews: 150,
    ratePerHour: 26,
    bio: "CPR certified, focused on safety and fun.",
    specialties: ["Babysitting", "Newborn Care"],
    availability: ["Fri", "Sat"],
    distance: 1.5,
    tags: ["baby"],
    img: "https://i.pravatar.cc/150?img=34",
  ),
];
