import 'package:cloud_firestore/cloud_firestore.dart';

import 'sitter.dart';

final List<Sitter> sitterList = [
  Sitter(
    id: "sarah_johnson",
    name: "Sarah Johnson",
    bio: "Experienced babysitter with newborn care expertise.",
    contactNumber: "0400 111 111",
    suburb: "Bondi",
    careTypes: const ["baby"],
    services: const ["Babysitting", "Newborn Care"],
    specialties: const ["Babysitting", "Newborn Care"],
    availabilitySlots: const [
      AvailabilitySlot(date: "2025-01-10", slots: ["Morning", "Afternoon"]),
      AvailabilitySlot(date: "2025-01-12", slots: ["Evening"]),
    ],
    availability: const [
      "2025-01-10: Morning, Afternoon",
      "2025-01-12: Evening",
    ],
    ratePerHour: 25,
    ratingAvg: 4.9,
    ratingCount: 127,
    isAvailable: true,
    profileImageUrl: "https://i.pravatar.cc/150?img=14",
    galleryImageUrls: const [],
    location: const GeoPoint(-33.8915, 151.2767),
    distance: 0.8,
  ),
  Sitter(
    id: "mike_chen",
    name: "Mike Chen",
    bio: "Pet lover, certified in dog walking & care.",
    contactNumber: "0400 222 222",
    suburb: "Chatswood",
    careTypes: const ["pet"],
    services: const ["Pet Sitting", "Dog Walking"],
    specialties: const ["Pet Sitting", "Dog Walking"],
    availabilitySlots: const [
      AvailabilitySlot(date: "2025-01-09", slots: ["Afternoon"]),
      AvailabilitySlot(date: "2025-01-13", slots: ["Morning", "Evening"]),
    ],
    availability: const [
      "2025-01-09: Afternoon",
      "2025-01-13: Morning, Evening",
    ],
    ratePerHour: 20,
    ratingAvg: 4.8,
    ratingCount: 89,
    isAvailable: true,
    profileImageUrl: "https://i.pravatar.cc/150?img=12",
    galleryImageUrls: const [],
    location: const GeoPoint(-33.7969, 151.1832),
    distance: 1.2,
  ),
  Sitter(
    id: "emma_rodriguez",
    name: "Emma Rodriguez",
    bio: "Flexible sitter for both kids and pets.",
    contactNumber: "0400 333 333",
    suburb: "Newtown",
    careTypes: const ["baby", "pet"],
    services: const ["Babysitting", "Pet Sitting"],
    specialties: const ["Babysitting", "Pet Sitting"],
    availabilitySlots: const [
      AvailabilitySlot(date: "2025-01-11", slots: ["Morning"]),
      AvailabilitySlot(date: "2025-01-14", slots: ["Evening"]),
    ],
    availability: const [
      "2025-01-11: Morning",
      "2025-01-14: Evening",
    ],
    ratePerHour: 28,
    ratingAvg: 4.9,
    ratingCount: 203,
    isAvailable: true,
    profileImageUrl: "https://i.pravatar.cc/150?img=45",
    galleryImageUrls: const [],
    location: const GeoPoint(-33.8981, 151.1745),
    distance: 0.5,
  ),
  Sitter(
    id: "liam_brown",
    name: "Liam Brown",
    bio: "Energetic sitter great with kids and pets.",
    contactNumber: "0400 444 444",
    suburb: "Manly",
    careTypes: const ["baby", "pet"],
    services: const ["Babysitting", "Pet Sitting"],
    specialties: const ["Babysitting", "Pet Sitting"],
    availabilitySlots: const [
      AvailabilitySlot(date: "2025-01-08", slots: ["Morning", "Evening"]),
    ],
    availability: const [
      "2025-01-08: Morning, Evening",
    ],
    ratePerHour: 23,
    ratingAvg: 4.4,
    ratingCount: 75,
    isAvailable: true,
    profileImageUrl: "https://i.pravatar.cc/150?img=65",
    galleryImageUrls: const [],
    location: const GeoPoint(-33.8001, 151.2866),
    distance: 2.0,
  ),
  Sitter(
    id: "sophia_davis",
    name: "Sophia Davis",
    bio: "CPR certified, focused on safety and fun.",
    contactNumber: "0400 555 555",
    suburb: "Parramatta",
    careTypes: const ["baby"],
    services: const ["Babysitting", "Newborn Care"],
    specialties: const ["Babysitting", "Newborn Care"],
    availabilitySlots: const [
      AvailabilitySlot(date: "2025-01-07", slots: ["Afternoon", "Evening"]),
    ],
    availability: const [
      "2025-01-07: Afternoon, Evening",
    ],
    ratePerHour: 26,
    ratingAvg: 4.7,
    ratingCount: 150,
    isAvailable: true,
    profileImageUrl: "https://i.pravatar.cc/150?img=34",
    galleryImageUrls: const [],
    location: const GeoPoint(-33.8136, 151.0034),
    distance: 1.5,
  ),
];

